{% set name = "backends" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/backends-{{ version }}.tar.gz
  sha256: 929fb48872a950b1194b14a40427e5a4469b3ea5cf421a3d95ff28f48b35c26f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.0.0
    - setuptools-scm[toml] ==8.1.0
    - setuptools_scm_git_archive >=1.4.1
    - wheel >=0.33
    - numpy >=1.16
    - cython >=0.29
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.16
    - scipy >=1.3
    - plum-dispatch >=2.5.7
    - opt-einsum

test:
  imports:
    - lab
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wesselb/lab
  summary: A generic interface for linear algebra backends
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - wesselb
