{% set name = "backends" %}
{% set version = "1.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backends-{{ version }}.tar.gz
  sha256: c8daf06d13151728a7571ef20a9c4080a309f5156b69122a01b5af7fc0b59162

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=50.0
    - setuptools-scm >=6.0
    - setuptools_scm_git_archive
    - wheel >=0.33
    - numpy >=1.16
    - cython >=0.29
    - pip
  run:
    - python >=3.8
    - numpy >=1.16
    - scipy >=1.3
    - plum-dispatch >=2.3.5
    - opt-einsum

test:
  imports:
    - lab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/lab
  summary: A generic interface for linear algebra backends
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - wesselb
